version: '3.1'
services:
  odoo11:
    image: odoo:11
    depends_on:
      - psql
    ports:
      - "8089:8069"
      - "8000:8000"
    environment:
      - HOST=psql
      - PASSWORD=my_odoo
    volumes:
      #- odoo-odoo11-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
  psql:
    image: postgres:12
    ports:
      - "5454:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=my_odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-psql-data:/var/lib/postgresql/data/pgdata
volumes:
  #odoo-odoo11-data:
  odoo-psql-data: