version: '3.1'
services:
  odoo11:
    image: odoo:11
    depends_on:
      - psql
    ports:
      - "8089:8069"
    environment:
    - HOST=psql
    - PASSWORD=my_odoo
    volumes:
      - ./extra-addons:/mnt/extra-addons
  psql:
    image: postgres:11
    ports:
      - "5454:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=my_odoo
      - POSTGRES_USER=odoo
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "fer@email.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "9000:80"
    depends_on:
      - psql  
